name: "Continuous Integration"

on:
  push:
    branches:
      - develop
      - feature/add-ci-cd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install

      - name: Run Model Tests
        run: |
          make model-test

      - name: Run API Tests
        run: |
          make api-test
      - name: Build Docker image
        run: |
          docker build -t challenge-image:ci-${{ github.sha }} .
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker push challenge-image:ci-${{ github.sha }}
          docker logout
